// This script licensed under the MIT.
// http://orgachem.mit-license.org

/**
 * @fileoverview A class for container elements.
 * @author orga.chem.job@gmail.com (OrgaChem)
 */


var basePath = '../../lib';
var util = require(basePath + '/util');
var array = require(basePath + '/array');
var BlockElement = require(basePath + '/dom/BlockElement');
var ElementArray = require(basePath + '/dom/ElementArray');
var Paragraph = require(basePath + '/dom/Paragraph');
var Tag = require(basePath + '/dom/Tag');
var Link = require(basePath + '/dom/Link');



/**
 * Base class for container elements.  The element can be used as a chapter,
 * section and article.
 *
 * The structure is:
 * <ul>
 * <li>Caption
 * <li>Top contents
 *   <ul>
 *   <li>Container 1
 *   <li>Container 2
 *   <li>...
 *   </ul>
 * <li>Sub containers
 *   <ul>
 *   <li>Sub container 1
 *   <li>Sub container 2
 *   <li>...
 *   </ul>
 * </ul>
 *
 * @param {string} caption Caption.
 * @param {?string=} opt_refId Optional reference ID.  The ID is generated by
 *     the {@code caption}, if not given {@code opt_refId}.
 * @constructor
 * @extends {module:lib/dom/BlockElement}
 * @exports lib/dom/Container
 */
var Container = function(caption, opt_refId) {
  // TODO: Do not inherit BlockElement. Because the container do not allow to
  // add a Container as a top contents of a container, or it makes to be able to
  // support markdown.
  BlockElement.call(this);
  this.setCaption(caption);
  this.tag_ = new Tag(opt_refId || this.getReferenceId());
  this.topBlocks_ = new ElementArray(this);
  this.subContainers_ = new ElementArray(this);
};
util.inherits(Container, BlockElement);


/**
 * Default content publisher.
 * @type {module:lib/publishing/ContainerPublisher}
 */
Container.publisher = null;


/**
 * Caption of the container.
 * @type {string}
 * @private
 */
Container.prototype.caption_ = null;


/**
 * Tag of the container.
 * @type {module:lib/dom/Tag}
 * @private
 */
Container.prototype.tag_;


/**
 * Top contents of the container.
 * @type {module:lib/dom/ElementArray.<module:lib/dom/BlockElement>}
 * @private
 */
Container.prototype.topBlocks_ = null;


/**
 * Sub contents of the container.
 * @type {module:lib/dom/ElementArray.<module:lib/dom/BlockElement>}
 * @private
 */
Container.prototype.subContainers_ = null;


/**
 * Returns a parent container if exists.
 * @return {?module:lib/dom/Container} Parent container.
 */
Container.prototype.getParentContainer = function() {
  var parentElemArr;
  if (parentElemArr = this.getParent()) {
    return parentElemArr.getParent();
  }
  else {
    return null;
  }
};


// Methods for a caption {{{
/**
 * Returns a caption of the container.
 * @return {string} Caption of the container.
 */
Container.prototype.getCaption = function() {
  return this.caption_;
};


/**
 * Sets a caption of the container.  This method is chainable.
 * @param {string} caption of the container.
 * @return {module:lib/dom/Container} This instance.
 */
Container.prototype.setCaption = function(caption) {
  this.caption_ = caption;
  return this;
};
//}}}


// Methods about reference to a container {{{
/**
 * Returns a tag of the container.
 * @return {module:lib/dom/Tag} Tag of the container.
 */
Container.prototype.getTag = function() {
  return this.tag_;
};


/**
 * Returns a link to the container.
 * @return {module:lib/dom/Link} Link.
 */
Container.prototype.getLink = function() {
  return new Link(this.getReferenceId());
};


/**
 * Returns a reference ID.
 * @return {string} Reference ID.
 */
Container.prototype.getReferenceId = function() {
  return this.tag_ ? this.tag_.getReferenceId() : this.getReferenceIdInternal(
      this.getCaption());
};


/**
 * Returns a reference ID by a caption.  This ID is made by the caption.  For
 * example, a caption that is {@code 'The caption example'} becomes {@code
 * 'the-caption-example'}.
 * @param {string} caption Caption.
 * @return {string} Reference ID.
 * @protected
 */
Container.prototype.getReferenceIdInternal = function(caption) {
  return caption.replace(/([a-z])([A-Z])/g, '$1_$2').replace(/\s+/g, '-').
      toLowerCase();
};
//}}}


// Methods for a parent and children relationship {{{


/**
 * Returns containers as descendants of the container.
 * @return {Array.<module:lib/dom/Container>} Descendant contents.
 */
Container.prototype.getDescendantContainers = function() {
  var descendants = [];
  this.getSubContainers().getChildren().forEach(function(sub) {
    descendants.push(sub);
    descendants = descendants.concat(sub.getDescendantContainers());
  });

  return descendants;
};


/**
 * Returns containers as ascendors of the container.
 * @return {Array.<module:lib/dom/Container>} Ancestor contents.
 */
Container.prototype.getAncestorContainers = function() {
  var ancestors = [];
  var container = this;

  while (container = container.getParentContainer()) {
    ancestors.unshift(container);
  }

  return ancestors;
};


/**
 * Returns an index number of the content.
 * @return {number} Index of the content.
 */
Container.prototype.getIndex = function() {
  var parent;
  if (parent = this.getParentContainer()) {
    return parent.getSubContainers().getChildren().indexOf(this);
  }

  return -1;
};


/**
 * Returns a depth of the container.
 * @return {number} Depth of the container.
 */
Container.prototype.getDepth = function() {
  var container = this;
  var depth = 0;

  while (container = container.getParentContainer()) {
    ++depth;
  }

  return depth;
};
//}}}


// Methods for top contents manipulation {{{
/**
 * Returns top block contents.
 * @return {module:lib/dom/ElementArray.<module:lib/dom/BlockElement>}
 *     Block contents on the top.
 */
Container.prototype.getTopElements = function() {
  return this.topBlocks_;
};
//}}}


/**
 * Returns sub contents.
 * @return {module:lib/dom/ElementArray.<module:lib/dom/BlockElement>}
 *     Containers as children of the container.
 */
Container.prototype.getSubContainers = function() {
  return this.subContainers_;
};


// Exports the constructor.
module.exports = Container;
